[package]
name = "metrics"
version = "0.0.3"
authors = ["Endre Karlson <endre.karlson@gmail.com>", "Alex Newman <posix4e@gmail.com>"]
description = "Coda Hale style metrics for rust"

documentation = "https://github.com/posix4e/rust-metrics/"
homepage = "https://github.com/posix4e/rust-metrics/"
repository = "https://github.com/posix4e/rust-metrics/"
readme = "README.md"
keywords = ["metrics", "graphite", "ganglia", "opentsdb"]
license = "Apache-2.0"

[dependencies]
time = "0.1.35"
num = "0.1.32"
histogram =  "0.3.6"
log = "0.3.6"
