version: '2'
services:

  local_webserver: 
    build: .
    entrypoint: ./bin/ws
    ports:
      - "3000:3000"
    expose:
      - "9090"

  prometheus:
    build: prometheus_support
    depends_on:
      - local_webserver
    ports:
      - "9090:9090"
    links:
      -  local_webserver

  carbon_graphite:
    image: rvernica/graphite
    ports:
       - "8080:8080"
    expose:
       - "2003"
    depends_on:
      - local_webserver
    links:
      -  local_webserver
